[phases.build]
cmds = [
  "npm ci",
  "npm run build",
  "cp -r public .next/standalone/",
  "cp -r .next/static .next/standalone/.next/"
]

[start]
cmd = "HOSTNAME=0.0.0.0 node .next/standalone/server.js"
